# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List
from typing_extensions import Annotated, TypedDict

from .._utils import PropertyInfo
from .webhook_trigger import WebhookTrigger
from .webhook_delivery import WebhookDelivery
from .webhook_response import WebhookResponse

__all__ = ["WebhookUpdateParams"]


class WebhookUpdateParams(TypedDict, total=False):
    active: bool
    """Boolean to indicate if the webhook is active"""

    deliveries: List[WebhookDelivery]

    responses: List[WebhookResponse]

    secret: str
    """A 24-character secret for the webhook.

    It's generated by Firefly III when saving a new webhook. If you submit a new
    secret through the PUT endpoint it will generate a new secret for the selected
    webhook, a new secret bearing no relation to whatever you just submitted.
    """

    title: str
    """A title for the webhook for easy recognition."""

    triggers: List[WebhookTrigger]

    url: str
    """The URL of the webhook. Has to start with `https`."""

    x_trace_id: Annotated[str, PropertyInfo(alias="X-Trace-Id")]
