# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime

from .._models import BaseModel
from .object_link import ObjectLink
from .webhook_trigger import WebhookTrigger
from .webhook_delivery import WebhookDelivery
from .webhook_response import WebhookResponse

__all__ = ["Webhook", "Attributes"]


class Attributes(BaseModel):
    delivery: object

    response: object

    title: str
    """A title for the webhook for easy recognition."""

    trigger: object

    url: str
    """The URL of the webhook. Has to start with `https`."""

    active: Optional[bool] = None
    """Boolean to indicate if the webhook is active"""

    created_at: Optional[datetime] = None

    deliveries: Optional[List[WebhookDelivery]] = None

    responses: Optional[List[WebhookResponse]] = None

    secret: Optional[str] = None
    """A 24-character secret for the webhook.

    It's generated by Firefly III when saving a new webhook. If you submit a new
    secret through the PUT endpoint it will generate a new secret for the selected
    webhook, a new secret bearing no relation to whatever you just submitted.
    """

    triggers: Optional[List[WebhookTrigger]] = None

    updated_at: Optional[datetime] = None


class Webhook(BaseModel):
    id: str

    attributes: Attributes

    links: ObjectLink

    type: str
    """Immutable value"""
