# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime

from ..._models import BaseModel
from ..array_entry_with_currency_and_sum import ArrayEntryWithCurrencyAndSum

__all__ = ["BudgetLimitRead", "Attributes"]


class Attributes(BaseModel):
    amount: Optional[str] = None

    budget_id: Optional[str] = None
    """The budget ID of the associated budget."""

    created_at: Optional[datetime] = None

    currency_code: Optional[str] = None
    """The currency code of the currency associated with this object."""

    currency_decimal_places: Optional[int] = None

    currency_id: Optional[str] = None
    """The currency ID of the currency associated with this object."""

    currency_name: Optional[str] = None
    """The currency name of the currency associated with this object."""

    currency_symbol: Optional[str] = None

    end: Optional[datetime] = None
    """End date of the budget limit."""

    notes: Optional[str] = None
    """Some notes for this specific budget limit."""

    object_has_currency_setting: Optional[bool] = None
    """Indicates whether the object has a currency setting.

    If false, the object uses the administration's primary currency.
    """

    pc_amount: Optional[str] = None
    """
    The amount of this budget limit in the user's primary currency, if the original
    amount is in a different currency.
    """

    pc_spent: Optional[List[ArrayEntryWithCurrencyAndSum]] = None
    """Amount(s) spent in the primary currency in the database for this budget limit."""

    period: Optional[str] = None
    """Period of the budget limit. Only used when auto-generated by auto-budget."""

    primary_currency_code: Optional[str] = None
    """The currency code of the administration's primary currency."""

    primary_currency_decimal_places: Optional[int] = None
    """The currency decimal places of the administration's primary currency."""

    primary_currency_id: Optional[str] = None
    """The currency ID of the administration's primary currency."""

    primary_currency_name: Optional[str] = None
    """The currency name of the administration's primary currency."""

    primary_currency_symbol: Optional[str] = None
    """The currency symbol of the administration's primary currency."""

    spent: Optional[List[ArrayEntryWithCurrencyAndSum]] = None
    """Amount(s) spent in the currencies in the database for this budget limit."""

    start: Optional[datetime] = None
    """Start date of the budget limit."""

    updated_at: Optional[datetime] = None


class BudgetLimitRead(BaseModel):
    id: str

    attributes: Attributes

    type: str
    """Immutable value"""
